"""
07_sintesis_resultados.py — Results Synthesis and Final Visualizations

Generates final comparative figures and summary tables from saved model outputs.

Visualizations (outputs/graficos/):
  1. Coefficient comparison: β for n_procedures (neoplasm vs sepsis) + CI95%
  2. OLS residual distributions (histogram + KDE)
  3. Predicted vs observed days_stay scatter (top 5 hospitals)
  4. Heatmap of hospital fixed effects

Summary tables (outputs/tablas/):
  - tabla_comparativa_neoplasia_vs_sepsis.csv

Inputs (from previous scripts):
  - outputs/tablas/coeficientes_regresion_logistica.csv
  - outputs/tablas/coeficientes_regresion_ols.csv
  - outputs/tablas/resultados_kruskal_wallis.csv
"""

import logging
import os
import sys

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import scipy.stats as sp_stats
import seaborn as sns

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import (
    ALPHA, COL_HOSPITAL, COL_SEVERITY, FIGURE_DPI, FIGURE_STYLE,
    GRAFICOS_DIR, MODELOS_DIR, TABLAS_DIR,
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
)
logger = logging.getLogger(__name__)

try:
    plt.style.use(FIGURE_STYLE)
except OSError:
    plt.style.use('seaborn-whitegrid')


# ── Load saved tables ─────────────────────────────────────────────────────────

def load_tables() -> dict:
    """Load result tables generated by previous scripts."""
    tables = {}
    files = {
        'logit':    os.path.join(TABLAS_DIR, 'coeficientes_regresion_logistica.csv'),
        'ols':      os.path.join(TABLAS_DIR, 'coeficientes_regresion_ols.csv'),
        'kruskal':  os.path.join(TABLAS_DIR, 'resultados_kruskal_wallis.csv'),
        'shapiro':  os.path.join(TABLAS_DIR, 'resultados_shapiro_wilk.csv'),
    }
    for key, path in files.items():
        if os.path.exists(path):
            tables[key] = pd.read_csv(path)
            logger.info("Loaded: %s (%d rows)", path, len(tables[key]))
        else:
            logger.warning("File not found: %s", path)
            tables[key] = None
    return tables


# ── Figure 1: Coefficient comparison n_procedures ────────────────────────────

def plot_coef_comparison(tables: dict) -> None:
    """Side-by-side bar chart: β for n_procedures in logit and OLS, both groups."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.suptitle(
        'Effect of Procedure Intensity (n_procedures)\nNeoplasm vs. Sepsis',
        fontsize=13, fontweight='bold',
    )

    for ax, model_key, model_name in [
        (axes[0], 'logit', 'Logistic (Mortality)'),
        (axes[1], 'ols',   'OLS (Days Stay)'),
    ]:
        df = tables.get(model_key)
        if df is None:
            ax.set_title(f'{model_name} — data not available')
            continue

        row_neo = df[(df['diagnostic_group'] == 'Neoplasm') & (df['variable'] == 'n_procedures')]
        row_sep = df[(df['diagnostic_group'] == 'Sepsis')   & (df['variable'] == 'n_procedures')]

        groups  = ['Neoplasm', 'Sepsis']
        coefs   = []
        ci_errs = []
        colors  = ['#2196F3', '#FF5722']

        for row in [row_neo, row_sep]:
            if row.empty:
                coefs.append(0)
                ci_errs.append(0)
            else:
                coef = row.iloc[0]['coef']
                lo   = row.iloc[0]['CI95_lower']
                hi   = row.iloc[0]['CI95_upper']
                coefs.append(coef)
                ci_errs.append([(coef - lo), (hi - coef)])

        x = np.arange(len(groups))
        bars = ax.bar(x, coefs, color=colors, alpha=0.8, width=0.5)

        # Error bars
        for i, (coef, (err_lo, err_hi)) in enumerate(zip(coefs, ci_errs)):
            ax.errorbar(x[i], coef, yerr=[[err_lo], [err_hi]], fmt='none',
                        color='black', capsize=6, linewidth=1.5)

        ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)
        ax.set_xticks(x)
        ax.set_xticklabels(groups, fontsize=11)
        ax.set_title(f'{model_name}', fontsize=11)
        ax.set_ylabel('Coefficient (β) ± CI95%')
        ax.set_xlabel('Diagnostic Group')

        # Significance annotations
        for i, row_df in enumerate([row_neo, row_sep]):
            if not row_df.empty:
                sig = row_df.iloc[0].get('sig', '')
                ax.text(x[i], coefs[i] + (0.005 if coefs[i] >= 0 else -0.005),
                        sig, ha='center', va='bottom' if coefs[i] >= 0 else 'top',
                        fontsize=12, fontweight='bold')

    plt.tight_layout()
    path = os.path.join(GRAFICOS_DIR, '07_coef_comparison.png')
    fig.savefig(path, dpi=FIGURE_DPI, bbox_inches='tight')
    plt.close(fig)
    logger.info("Saved: %s", path)


# ── Figure 2: Residual distributions ─────────────────────────────────────────

def plot_residuals(df_neo: pd.DataFrame, df_sep: pd.DataFrame) -> None:
    """Histogram + KDE + Q-Q plot for OLS residuals."""
    from utils import clean_data, derive_variables, filter_diagnostic_groups, free_memory, load_grd_data
    import statsmodels.formula.api as smf
    import warnings; warnings.filterwarnings('ignore')

    COLUMNS_NEEDED = [
        COL_HOSPITAL, 'FECHA_NACIMIENTO', 'FECHA_INGRESO', 'FECHAALTA',
        'TIPOALTA', 'DIAGNOSTICO1', 'IR_29301_SEVERIDAD', 'IR_29301_PESO',
    ] + [f'PROCEDIMIENTO{i}' for i in range(1, 31)]

    fig, axes = plt.subplots(2, 2, figsize=(14, 11))
    fig.suptitle('OLS Residual Diagnostics', fontsize=13, fontweight='bold')

    for i, (df, label) in enumerate([(df_neo, 'Neoplasm'), (df_sep, 'Sepsis')]):
        req = ['days_stay', 'n_procedures', COL_SEVERITY, 'age', COL_HOSPITAL]
        df_m = df[req].dropna().copy()
        df_m[COL_SEVERITY] = pd.to_numeric(df_m[COL_SEVERITY], errors='coerce').dropna()
        df_m = df_m.dropna()
        df_m[COL_SEVERITY] = df_m[COL_SEVERITY].astype(int)

        if len(df_m) < 50:
            continue

        try:
            formula = f"days_stay ~ n_procedures + C({COL_SEVERITY}) + age + C({COL_HOSPITAL})"
            res = smf.ols(formula, data=df_m).fit()
            residuals = res.resid
        except Exception as e:
            logger.warning("Could not fit OLS for residuals plot [%s]: %s", label, e)
            continue

        # Histogram + KDE
        ax_hist = axes[i, 0]
        ax_hist.hist(residuals, bins=60, density=True, alpha=0.6,
                     color='steelblue' if i == 0 else 'coral')
        residuals.plot.kde(ax=ax_hist, color='navy' if i == 0 else 'darkred', linewidth=2)
        ax_hist.set_title(f'{label}: Residual Distribution')
        ax_hist.set_xlabel('Residuals (days)')
        ax_hist.set_ylabel('Density')

        # Q-Q plot
        ax_qq = axes[i, 1]
        sp_stats.probplot(residuals, dist='norm', plot=ax_qq)
        ax_qq.set_title(f'{label}: Q-Q Plot of Residuals')
        ax_qq.get_lines()[0].set(markersize=2, alpha=0.4)

    plt.tight_layout()
    path = os.path.join(GRAFICOS_DIR, '08_residual_diagnostics.png')
    fig.savefig(path, dpi=FIGURE_DPI, bbox_inches='tight')
    plt.close(fig)
    logger.info("Saved: %s", path)


# ── Figure 3: Predicted vs Observed ──────────────────────────────────────────

def plot_pred_vs_obs(df_neo: pd.DataFrame, df_sep: pd.DataFrame) -> None:
    """Scatter: observed vs predicted days_stay (OLS), colored by hospital (top 5)."""
    import statsmodels.formula.api as smf
    import warnings; warnings.filterwarnings('ignore')

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle('Predicted vs. Observed Days Stay (OLS)', fontsize=13, fontweight='bold')

    for ax, df, label in [(axes[0], df_neo, 'Neoplasm'), (axes[1], df_sep, 'Sepsis')]:
        req = ['days_stay', 'n_procedures', COL_SEVERITY, 'age', COL_HOSPITAL]
        df_m = df[req].dropna().copy()
        df_m[COL_SEVERITY] = pd.to_numeric(df_m[COL_SEVERITY], errors='coerce')
        df_m = df_m.dropna()
        df_m[COL_SEVERITY] = df_m[COL_SEVERITY].astype(int)

        top5 = df_m[COL_HOSPITAL].value_counts().head(5).index.tolist()
        df_m = df_m[df_m[COL_HOSPITAL].isin(top5)]

        if len(df_m) < 50:
            continue

        try:
            formula = f"days_stay ~ n_procedures + C({COL_SEVERITY}) + age + C({COL_HOSPITAL})"
            res = smf.ols(formula, data=df_m).fit()
            predicted = res.fittedvalues
        except Exception as e:
            logger.warning("[%s] OLS for pred vs obs failed: %s", label, e)
            continue

        palette = dict(zip(top5, sns.color_palette('tab10', 5)))
        for hosp in top5:
            mask = df_m[COL_HOSPITAL] == hosp
            ax.scatter(
                df_m.loc[mask, 'days_stay'],
                predicted[mask],
                label=hosp, alpha=0.3, s=8, color=palette[hosp],
            )

        # Perfect prediction diagonal
        lims = [
            min(df_m['days_stay'].min(), predicted.min()),
            max(df_m['days_stay'].max(), predicted.max()),
        ]
        ax.plot(lims, lims, 'k--', linewidth=1.2, label='Perfect prediction')
        ax.set_xlim(lims)
        ax.set_ylim(lims)

        ax.set_title(f'{label}')
        ax.set_xlabel('Observed days_stay')
        ax.set_ylabel('Predicted days_stay')
        ax.legend(title='Hospital', fontsize=8, markerscale=3)

    plt.tight_layout()
    path = os.path.join(GRAFICOS_DIR, '09_pred_vs_obs.png')
    fig.savefig(path, dpi=FIGURE_DPI, bbox_inches='tight')
    plt.close(fig)
    logger.info("Saved: %s", path)


# ── Figure 4: Heatmap of hospital fixed effects ───────────────────────────────

def plot_hospital_heatmap(tables: dict) -> None:
    """Heatmap: hospital fixed effects from OLS models (neoplasm and sepsis)."""
    ols_df = tables.get('ols')
    if ols_df is None:
        logger.warning("OLS table not available for heatmap.")
        return

    # Extract hospital fixed effects
    hosp_rows = ols_df[ols_df['variable'].str.startswith(f'C({COL_HOSPITAL})')].copy()
    if hosp_rows.empty:
        logger.warning("No hospital fixed effects found in OLS table.")
        return

    hosp_rows['hospital'] = (
        hosp_rows['variable']
        .str.extract(r'\[T\.(.+)\]')
    )

    pivot = hosp_rows.pivot_table(
        index='hospital', columns='diagnostic_group', values='coef',
    )

    if pivot.empty:
        logger.warning("Pivot table for heatmap is empty.")
        return

    fig, ax = plt.subplots(figsize=(10, max(6, len(pivot) * 0.4)))
    sns.heatmap(
        pivot,
        cmap='RdBu_r', center=0, annot=True, fmt='.2f',
        linewidths=0.5, ax=ax, cbar_kws={'label': 'Fixed Effect (days)'},
    )
    ax.set_title('Hospital Fixed Effects by Diagnostic Group (OLS)', fontsize=12, fontweight='bold')
    ax.set_xlabel('Diagnostic Group')
    ax.set_ylabel('Hospital Code')

    plt.tight_layout()
    path = os.path.join(GRAFICOS_DIR, '10_hospital_heatmap.png')
    fig.savefig(path, dpi=FIGURE_DPI, bbox_inches='tight')
    plt.close(fig)
    logger.info("Saved: %s", path)


# ── Comparative summary table ─────────────────────────────────────────────────

def build_comparative_table(tables: dict) -> pd.DataFrame:
    """Build a summary table comparing results across hypotheses and groups."""
    rows = []

    # H1 — Kruskal-Wallis
    kw = tables.get('kruskal')
    if kw is not None:
        for _, r in kw.iterrows():
            rows.append({
                'hypothesis': 'H1 (Kruskal-Wallis)',
                'test':       'Kruskal-Wallis',
                'variable':   r['variable'],
                'group':      r['diagnostic_group'],
                'stat':       r.get('H_stat', ''),
                'p_value':    r.get('p_display', ''),
                'sig':        r.get('sig', ''),
                'conclusion': r.get('conclusion', ''),
            })

    # H2 — Logistic (n_procedures row)
    logit = tables.get('logit')
    if logit is not None:
        for _, r in logit[logit['variable'] == 'n_procedures'].iterrows():
            rows.append({
                'hypothesis': 'H2 (Logistic)',
                'test':       'Logit + fixed effects',
                'variable':   'n_procedures → mortality',
                'group':      r['diagnostic_group'],
                'stat':       r.get('coef', ''),
                'p_value':    r.get('p_display', ''),
                'sig':        r.get('sig', ''),
                'conclusion': (
                    f"OR={r.get('OR', '')} CI95%=[{r.get('CI95_lower', '')}, {r.get('CI95_upper', '')}]"
                ),
            })

    # H3 — OLS (n_procedures row)
    ols = tables.get('ols')
    if ols is not None:
        for _, r in ols[ols['variable'] == 'n_procedures'].iterrows():
            rows.append({
                'hypothesis': 'H3 (OLS)',
                'test':       'OLS + fixed effects',
                'variable':   'n_procedures → days_stay',
                'group':      r['diagnostic_group'],
                'stat':       r.get('coef', ''),
                'p_value':    r.get('p_display', ''),
                'sig':        r.get('sig', ''),
                'conclusion': (
                    f"CI95%=[{r.get('CI95_lower', '')}, {r.get('CI95_upper', '')}]"
                ),
            })

    df = pd.DataFrame(rows)
    return df


def main():
    logger.info("=== 07_sintesis_resultados.py START ===")

    os.makedirs(GRAFICOS_DIR, exist_ok=True)
    os.makedirs(TABLAS_DIR, exist_ok=True)

    tables = load_tables()

    # Need cleaned data for residual / prediction plots
    from utils import (
        clean_data, derive_variables, filter_diagnostic_groups,
        free_memory, load_grd_data,
    )
    COLUMNS_NEEDED = [
        COL_HOSPITAL, 'FECHA_NACIMIENTO', 'FECHA_INGRESO', 'FECHAALTA',
        'TIPOALTA', 'DIAGNOSTICO1', 'IR_29301_SEVERIDAD', 'IR_29301_PESO',
    ] + [f'PROCEDIMIENTO{i}' for i in range(1, 31)]

    raw = load_grd_data(usecols=COLUMNS_NEEDED)
    raw = derive_variables(raw)
    df_neo, df_sep = filter_diagnostic_groups(raw)
    free_memory(raw)
    df_neo = clean_data(df_neo, 'neoplasm')
    df_sep = clean_data(df_sep, 'sepsis')

    # Generate visualizations
    plot_coef_comparison(tables)
    plot_residuals(df_neo, df_sep)
    plot_pred_vs_obs(df_neo, df_sep)
    plot_hospital_heatmap(tables)

    # Comparative table
    comp_table = build_comparative_table(tables)
    out_path = os.path.join(TABLAS_DIR, 'tabla_comparativa_neoplasia_vs_sepsis.csv')
    comp_table.to_csv(out_path, index=False)
    logger.info("Comparative table saved: %s", out_path)

    print("\n=== COMPARATIVE SUMMARY TABLE ===")
    print(comp_table.to_string(index=False))

    logger.info("=== 07_sintesis_resultados.py COMPLETE ===")


if __name__ == '__main__':
    main()
